"""Generate the SQL grammar and schema prompt from the frozen database.

Reads db/creg.sqlite (the authoritative schema + data) and emits two CREGKit
resources:

  sql_grammar.ebnf   XGrammar EBNF for grammar-constrained decoding:
                     SELECT-only, real table/column names as terminals,
                     CTE names restricted to cte/cte1..cte9 so a FROM clause
                     can never reference a hallucinated table.
  schema_prompt.txt  Compact schema serialization for the model prompt,
                     with enumerated values for low-cardinality TEXT columns
                     (prompt-side value grounding).

Free-text string literals stay unconstrained in the grammar (needed for LIKE
patterns and names); wrong literals are handled by the fuzzy-match correction
heuristic, not the grammar. See PRD §9 caveat.

Usage:  uv run python tools/generate_grammar.py
"""

import sqlite3
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DB_PATH = REPO_ROOT / "db" / "creg.sqlite"
RESOURCE_DIR = REPO_ROOT / "CREGKit" / "Sources" / "CREGEngine" / "Resources"
ENUM_CARDINALITY_CAP = 12

GRAMMAR_TEMPLATE = r"""# CREG SQL grammar — GENERATED by tools/generate_grammar.py from db/creg.sqlite.
# Do not edit by hand. SELECT-only by construction; identifiers are enumerated.

root ::= ows select_stmt ows

select_stmt ::= (with_clause ws)? select_core (ws order_clause)? (ws limit_clause)?

with_clause ::= "WITH" ws cte (ows "," ows cte)*
cte ::= cte_name ws "AS" ows "(" ows select_stmt ows ")"
cte_name ::= "cte" [0-9]?

select_core ::= "SELECT" ws ("DISTINCT" ws)? result_list ws "FROM" ws from_clause (ws "WHERE" ws expr)? (ws "GROUP BY" ws expr_list)? (ws "HAVING" ws expr)?

result_list ::= result_col (ows "," ows result_col)*
result_col ::= "*" | qualifier "." "*" | expr (ws "AS" ws (alias | string))?

from_clause ::= table_ref (join_clause)*
table_ref ::= (table_name | cte_name) (ws ("AS" ws)? alias)? | "(" ows select_stmt ows ")" (ws ("AS" ws)? alias)?
join_clause ::= ws (("LEFT" | "INNER" | "CROSS") ws)? "JOIN" ws table_ref ws join_constraint
join_constraint ::= "ON" ws expr | "USING" ows "(" ows column_name (ows "," ows column_name)* ows ")"

order_clause ::= "ORDER BY" ws ordering_term (ows "," ows ordering_term)*
ordering_term ::= expr (ws ("ASC" | "DESC"))?
limit_clause ::= "LIMIT" ws integer (ws "OFFSET" ws integer)?

expr_list ::= expr (ows "," ows expr)*
expr ::= and_expr (ws "OR" ws and_expr)*
and_expr ::= not_expr (ws "AND" ws not_expr)*
not_expr ::= ("NOT" ws)? predicate
predicate ::= concat (predicate_tail)?
predicate_tail ::= ows compare_op ows concat
  | ws ("NOT" ws)? "BETWEEN" ws concat ws "AND" ws concat
  | ws ("NOT" ws)? "IN" ows "(" ows (select_stmt | expr_list) ows ")"
  | ws ("NOT" ws)? "LIKE" ws concat
  | ws "IS" ws ("NOT" ws)? "NULL"
compare_op ::= "=" | "!=" | "<>" | "<=" | ">=" | "<" | ">"
concat ::= additive (ows "||" ows additive)*
additive ::= multiplicative (ows ("+" | "-") ows multiplicative)*
multiplicative ::= unary (ows ("*" | "/" | "%") ows unary)*
unary ::= ("-" ows)? primary
primary ::= number | string | "NULL" | func_call | column_ref | case_expr | "(" ows (select_stmt | expr) ows ")" | alias

column_ref ::= (qualifier ".")? column_name
qualifier ::= table_name | cte_name | alias
alias ::= [a-z] [a-z0-9_]*

func_call ::= agg_call | scalar_call | window_call
agg_call ::= agg_name ows "(" ows ("*" | ("DISTINCT" ws)? expr) ows ")" (over_clause)?
agg_name ::= "COUNT" | "SUM" | "AVG" | "MIN" | "MAX" | "TOTAL"
scalar_call ::= "ROUND" ows "(" ows expr (ows "," ows expr)? ows ")"
  | "ABS" ows "(" ows expr ows ")"
  | "LENGTH" ows "(" ows expr ows ")"
  | "LOWER" ows "(" ows expr ows ")"
  | "UPPER" ows "(" ows expr ows ")"
  | "COALESCE" ows "(" ows expr_list ows ")"
  | "NULLIF" ows "(" ows expr ows "," ows expr ows ")"
  | "IIF" ows "(" ows expr ows "," ows expr ows "," ows expr ows ")"
  | "SUBSTR" ows "(" ows expr ows "," ows expr (ows "," ows expr)? ows ")"
  | "STRFTIME" ows "(" ows string ows "," ows expr ows ")"
  | "DATE" ows "(" ows expr (ows "," ows string)* ows ")"
  | "JULIANDAY" ows "(" ows expr ows ")"
  | "CAST" ows "(" ows expr ws "AS" ws type_name ows ")"
type_name ::= "INTEGER" | "REAL" | "TEXT"
window_call ::= ("ROW_NUMBER" | "RANK" | "DENSE_RANK") ows "(" ows ")" over_clause
  | "NTILE" ows "(" ows integer ows ")" over_clause
over_clause ::= ws "OVER" ows "(" ows ("PARTITION BY" ws expr_list)? (ows "ORDER BY" ws ordering_term (ows "," ows ordering_term)*)? ows ")"

case_expr ::= "CASE" (ws expr)? (ws "WHEN" ws expr ws "THEN" ws expr)+ (ws "ELSE" ws expr)? ws "END"

table_name ::= {table_names}
column_name ::= {column_names}

string ::= "'" [^']* "'"
integer ::= [0-9]+
number ::= [0-9]+ ("." [0-9]+)?
ws ::= [ \t\n]+
ows ::= [ \t\n]*
"""


def alternation(names: list[str]) -> str:
    return " | ".join(f'"{n}"' for n in names)


def main() -> None:
    conn = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    tables = [
        r[0] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
    ]

    columns: dict[str, list[str]] = {}
    for table in tables:
        columns[table] = [r[1] for r in conn.execute(f"PRAGMA table_info({table})")]

    # Longest-first keeps greedy prefix alternatives from shadowing longer names.
    all_columns = sorted({c for cols in columns.values() for c in cols}, key=len, reverse=True)
    table_names = sorted(tables, key=len, reverse=True)

    grammar = GRAMMAR_TEMPLATE.format(
        table_names=alternation(table_names),
        column_names=alternation(all_columns),
    )

    # Compact schema prompt with FK arrows and enumerated low-cardinality values.
    lines = []
    for table in tables:
        fks = {r[3]: f"{r[2]}.{r[4]}" for r in conn.execute(f"PRAGMA foreign_key_list({table})")}
        parts = []
        for col in columns[table]:
            entry = col
            if col in fks:
                entry += f"->{fks[col]}"
            else:
                is_text = conn.execute(
                    f"SELECT type FROM pragma_table_info('{table}') WHERE name=?", (col,)
                ).fetchone()[0].upper() == "TEXT"
                if is_text:
                    values = [r[0] for r in conn.execute(
                        f"SELECT DISTINCT {col} FROM {table} WHERE {col} IS NOT NULL ORDER BY 1")]
                    if 0 < len(values) <= ENUM_CARDINALITY_CAP and all(len(str(v)) <= 24 for v in values):
                        entry += "[" + ",".join(f"'{v}'" for v in values) + "]"
            parts.append(entry)
        lines.append(f"{table}({', '.join(parts)})")
    schema_prompt = "\n".join(lines) + "\n"

    RESOURCE_DIR.mkdir(parents=True, exist_ok=True)
    (RESOURCE_DIR / "sql_grammar.ebnf").write_text(grammar)
    (RESOURCE_DIR / "schema_prompt.txt").write_text(schema_prompt)
    print(f"wrote {RESOURCE_DIR / 'sql_grammar.ebnf'} ({len(grammar)} chars)")
    print(f"wrote {RESOURCE_DIR / 'schema_prompt.txt'} ({len(schema_prompt)} chars)")


if __name__ == "__main__":
    main()
