"""Validate the gold set: execute every gold SQL, check grammar acceptance,
and emit a judge-review report.

Checks per item:
  - SQL executes without error against db/creg.sqlite
  - result is non-degenerate (rows > 0, not a single NULL scalar) unless
    the item is tagged to allow it
  - SQL is accepted by the decoding grammar (sql_grammar.ebnf) — a gold
    query the grammar cannot represent means the grammar is too tight

Writes a markdown review table for the judge pass.

Usage:  uv run python tools/validate_gold.py [--gold PATH] [--report PATH]
"""

import argparse
import json
from pathlib import Path

import xgrammar
from xgrammar.testing import _is_grammar_accept_string as grammar_accepts

from eval.ex import ExecutionError, execute

REPO_ROOT = Path(__file__).resolve().parents[2]
DB = REPO_ROOT / "db" / "creg.sqlite"
GRAMMAR = REPO_ROOT / "CREGKit" / "Sources" / "CREGEngine" / "Resources" / "sql_grammar.ebnf"
DEFAULT_GOLD = REPO_ROOT / "eval" / "gold" / "gold_v1.jsonl"
DEFAULT_REPORT = REPO_ROOT / "docs" / "gold-review-v1.md"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--gold", type=Path, default=DEFAULT_GOLD)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    args = parser.parse_args()

    grammar = xgrammar.Grammar.from_ebnf(GRAMMAR.read_text())
    items = [json.loads(line) for line in args.gold.read_text().splitlines() if line.strip()]

    lines = [
        "# Gold set review — " + args.gold.name,
        "",
        "Generated by tools/validate_gold.py. Columns: rows returned, grammar",
        "acceptance, flags needing judge attention, first result row.",
        "",
        "| id | tier | rows | grammar | flags | first row |",
        "|---|---|---|---|---|---|",
    ]
    problems = 0
    for item in items:
        flags = []
        rows = None
        try:
            rows = execute(DB, item["sql"])
        except ExecutionError as error:
            flags.append(f"EXEC-ERROR: {error}")
        in_grammar = grammar_accepts(grammar, item["sql"])
        if not in_grammar:
            flags.append("NOT-IN-GRAMMAR")
        if rows is not None:
            if len(rows) == 0:
                flags.append("EMPTY")
            elif len(rows) == 1 and all(v is None for v in rows[0]):
                flags.append("NULL-SCALAR")
        if flags:
            problems += 1
        first = "" if not rows else str(rows[0])[:60].replace("|", "\\|")
        lines.append(
            f"| {item['id']} | {item['tier']} | {'-' if rows is None else len(rows)} "
            f"| {'ok' if in_grammar else 'NO'} | {'; '.join(flags) or 'ok'} | {first} |"
        )

    tiers: dict[int, int] = {}
    for item in items:
        tiers[item["tier"]] = tiers.get(item["tier"], 0) + 1
    lines += [
        "",
        f"**{len(items)} items** (tiers: {dict(sorted(tiers.items()))}), "
        f"**{problems} flagged** for judge attention.",
        "",
    ]
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text("\n".join(lines))
    print(f"{len(items)} items, {problems} flagged -> {args.report}")


if __name__ == "__main__":
    main()
